### ISSUE TITLE
외부인 좋아요 Alert

### ISSUE THREAD

**Issue by hammii** [choib1ack/AISW_Web_Community#161]
좋아요 눌렀을 때 Alert 오류 처리 해야함
"좋아요를 누를 권한이 없습니다! 로그인 해주세요!"처럼 알림해야함

**Comment by Yangheerim** [comment]
현재 서버 에러 500코드로 응답됨. 
서버에서 **'권한없음'** 처리 해줘야할 듯
![image](https://user-images.githubusercontent.com/37904738/131780857-a49d8f3b-65f1-4385-a01c-f9651e9cdd0b.png)

**Comment by choib1ack** [comment]
수정 완료
